package database;
// Generated Jun 7, 2017 5:07:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hall generated by hbm2java
 */
@Entity
@Table(name="hall"
    ,catalog="projekat"
)
public class Hall  implements java.io.Serializable {


     private Integer hid;
     private Location location;
     private String name;
     private Set<Session> sessions = new HashSet<Session>(0);

    public Hall() {
    }

	
    public Hall(Location location) {
        this.location = location;
    }
    public Hall(Location location, String name, Set<Session> sessions) {
       this.location = location;
       this.name = name;
       this.sessions = sessions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="hid", unique=true, nullable=false)
    public Integer getHid() {
        return this.hid;
    }
    
    public void setHid(Integer hid) {
        this.hid = hid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lid", nullable=false)
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }

    
    @Column(name="name", length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hall")
    public Set<Session> getSessions() {
        return this.sessions;
    }
    
    public void setSessions(Set<Session> sessions) {
        this.sessions = sessions;
    }




}


