package database;
// Generated Jun 7, 2017 5:07:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name="location"
    ,catalog="projekat"
)
public class Location  implements java.io.Serializable {


     private Integer lid;
     private String name;
     private String address;
     private Set<Conference> conferences = new HashSet<Conference>(0);
     private Set<Hall> halls = new HashSet<Hall>(0);

    public Location() {
    }

    public Location(String name, String address, Set<Conference> conferences, Set<Hall> halls) {
       this.name = name;
       this.address = address;
       this.conferences = conferences;
       this.halls = halls;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="lid", unique=true, nullable=false)
    public Integer getLid() {
        return this.lid;
    }
    
    public void setLid(Integer lid) {
        this.lid = lid;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="address", length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="location")
    public Set<Conference> getConferences() {
        return this.conferences;
    }
    
    public void setConferences(Set<Conference> conferences) {
        this.conferences = conferences;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="location")
    public Set<Hall> getHalls() {
        return this.halls;
    }
    
    public void setHalls(Set<Hall> halls) {
        this.halls = halls;
    }




}


