package database;
// Generated Jun 7, 2017 5:07:06 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Moderator generated by hbm2java
 */
@Entity
@Table(name="moderator"
    ,catalog="projekat"
    , uniqueConstraints = @UniqueConstraint(columnNames={"mid", "cid", "uid"}) 
)
public class Moderator  implements java.io.Serializable {


     private Integer mid;
     private Conference conference;
     private User user;

    public Moderator() {
    }

    public Moderator(Conference conference, User user) {
       this.conference = conference;
       this.user = user;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="mid", unique=true, nullable=false)
    public Integer getMid() {
        return this.mid;
    }
    
    public void setMid(Integer mid) {
        this.mid = mid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cid", nullable=false)
    public Conference getConference() {
        return this.conference;
    }
    
    public void setConference(Conference conference) {
        this.conference = conference;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="uid", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


